PREFIX p: <http://Aniln.com>
PREFIX d: <http://Aniln.com/ns/data#>
        
  SELECT ?Nama ?Tipe ?Sinopsis ?Rilis ?Penerbit ?Status ?Genre ?Image ?JumlahEps ?Score

        WHERE
        { 
  			?s  d:nama ?Nama;
                d:sinopsis ?Sinopsis;
                d:airedPublished ?Rilis;
                d:studiosAuthor ?Penerbit;
                d:status ?Status;
                d:genre ?Genre;
                # d:image ?Image;
                d:episodeChapter ?JumlahEps;
                d:score ?Score.
  			?t 	d:jenis ?Tipe;
  				d:isJenis ?s.
        }